/**
 * @file TIMERS_Program.c
 * @author Khaled Abdulaziz 
 * @brief 
 * @version 0.1
 * @date 2023-04-05
 * 
 * 
 */

#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"

#include "TIMERS_Interface.h"
#include "TIMERS_Private.h"
#include "TIMERS_Config.h"

void TIMER0_voidInit()
{
    #if TIMER0_WAVEFORM_MODE == TIMER0_NORMAL
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_WGM00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_WGM01);

    #elif TIMER0_WAVEFORM_MODE == TIMER0_PWM_PHASE_CORRECT
    SET_BIT(TIMER0_TCCR0, TCCR0_WGM00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_WGM01);

    #elif TIMER0_WAVEFORM_MODE == TIMER0_CTC
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_WGM00);
    SET_BIT(TIMER0_TCCR0, TCCR0_WGM01);

    #elif TIMER0_WAVEFORM_MODE == TIMER0_FAST_PWM
    SET_BIT(TIMER0_TCCR0, TCCR0_WGM00);
    SET_BIT(TIMER0_TCCR0, TCCR0_WGM01);

    #endif

    #if TIMER0_OUTPUT_MODE == TIMER0_NORMAL_OC0_DISCONNECTED
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_COM00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_COM01);

    #elif TIMER0_WAVEFORM_MODE == TIMER0_TOGGLE_OC0
    	#if	TIMER0_WAVEFORM_MODE == TIMER0_PWM_PHASE_CORRECT || TIMER0_u8_WAVEFORM_MODE == TIMER0_FAST_PWM
		#warning ("RESERVED!")
		#else
        SET_BIT(TIMER0_TCCR0, TCCR0_COM00);
        CLEAR_BIT(TIMER0_TCCR0, TCCR0_COM01);
        #endif

    #elif TIMER0_WAVEFORM_MODE == TIMER0_CLEAR_OC0
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_COM00);
    SET_BIT(TIMER0_TCCR0, TCCR0_COM01);

    #elif TIMER0_WAVEFORM_MODE == TIMER0_SET_OC0
    SET_BIT(TIMER0_TCCR0, TCCR0_COM00);
    SET_BIT(TIMER0_TCCR0, TCCR0_COM01);

    #endif

    #if TIMER0_PRESCALER == TIMER0_STOP
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS01);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_1
    SET_BIT(TIMER0_TCCR0, TCCR0_CS00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS01);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_8
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS00);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS01);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_64
    SET_BIT(TIMER0_TCCR0, TCCR0_CS00);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS01);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_256
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS01);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_1024
    SET_BIT(TIMER0_TCCR0, TCCR0_CS00);
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS01);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_EXT_CLK_T0_FALLING
    CLEAR_BIT(TIMER0_TCCR0, TCCR0_CS00);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS01);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #elif TIMER0_PRESCALER == TIMER0_EXT_CLK_T0_RISISNG
    SET_BIT(TIMER0_TCCR0, TCCR0_CS00);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS01);
    SET_BIT(TIMER0_TCCR0, TCCR0_CS02);

    #endif

/*     #if TIMER0_INTERRUPT == TIMER0_ENABLE_INTERRUPT
    	#if TIMER0_u8_WAVEFORM_MODE == TIMER0_NORMAL
		SET_BIT(TIMERS_TIMSK, TIMSK_TOIE0);
		#elif TIMER0_u8_WAVEFORM_MODE == TIMER0_CTC
		SET_BIT(TIMERS_TIMSK, TIMSK_OCIE0);
    	#endif

    #elif TIMER0_INTERRUPT == TIMER0_DISABLE_INTERRUPT
    	#if TIMER0_WAVEFORM_MODE == TIMER0_NORMAL
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_TOIE0);
		#elif TIMER0_WAVEFORM_MODE == TIMER0_CTC
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_OCIE0);
    	#endif
    #endif */
}

void TIMER0_voidSetPreloadValue(u8 Copy_u8PreloadValue)
{
    TIMER0_TCNT0 = Copy_u8PreloadValue;
}

void TIMER0_voidSetCompareMatchValue(u8 Copy_u8CompareMatchValue)
{
    TIMER0_OCR0 = Copy_u8CompareMatchValue;
}

void TIMER0_voidSetOVFCallBack(void (*Local_pvoidCallBack) (void))
{
	Local_pvoidCallBackOVF = Local_pvoidCallBack;
}

void TIMER0_voidSetCTCCallBack(void (*Local_pvoidCallBack) (void))
{
	Local_pvoidCallBackCTC = Local_pvoidCallBack;
}

void __vector_11(void){
    if (Local_pvoidCallBackOVF != NULL)
    {
        Local_pvoidCallBackOVF();
    }
}

void __vector_10(void){
    if (Local_pvoidCallBackCTC != NULL)
    {
        Local_pvoidCallBackCTC();
    }
}

/*non inverting
 * perodic time = Over Flow time = tick time * OverFlow value
 * on time  = Compare time => compare Value *tick time  */

void TIMER1_voidInit(void)
{
    #if TIMER1_WAVEFORM_MODE == TIMER1_NORMAL
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_CORRECT_8BIT
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_CORRECT_9BIT
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_CORRECT_10BIT
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_CTC_OCR1A
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_FAST_PWM_8BIT
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_FAST_PWM_9BIT
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_FAST_PWM_10BIT
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_FREQUANCY_CORRECT_ICR1
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_FREQUANCY_CORRECT_OCR1A
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_CORRECT_ICR1
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_PWM_PHASE_CORRECT_OCR1A
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_CTC_ICR1
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_FAST_PWM_ICR1
		CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#elif TIMER1_WAVEFORM_MODE == TIMER1_FAST_PWM_OCR1A
		SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM10);
        SET_BIT(TIMER1_TCCR1A, TCCR1A_WGM11);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM12);
        SET_BIT(TIMER1_TCCR1B, TCCR1B_WGM13);
	#endif

    #ifdef TIMER1_CHANNEL_A_ENABLE
		#if	TIMER1_CHANNEL_A_OUTPUT_MODE == TIMER1_OC1_DISCONNECTED
			CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1A0);
            CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1A1);
		#elif TIMER1_CHANNEL_A_OUTPUT_MODE == TIMER1_OC1_TOGGLE
			SET_BIT(TCCR1A,COM1A0);
			CLEAR_BIT(TCCR1A,COM1A1);
		#elif TIMER1_CHANNEL_A_OUTPUT_MODE == TIMER1_OC1_CLEAR
            CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1A0);
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1A1);
		#elif TIMER1_CHANNEL_A_OUTPUT_MODE == TIMER1_OC1_SET
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1A0);
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1A1);
		#endif
	#endif

    #ifdef TIMER1_CHANNEL_B_ENABLE
		#if	TIMER1_CHANNEL_B_OUTPUT_MODE == TIMER1_OC1_DISCONNECTED
			CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1B0);
            CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1B1);
		#elif TIMER1_CHANNEL_B_OUTPUT_MODE == TIMER1_OC1_TOGGLE
			SET_BIT(TCCR1A,COM1B0);
			CLEAR_BIT(TCCR1A,COM1B1);
		#elif TIMER1_CHANNEL_B_OUTPUT_MODE == TIMER1_OC1_CLEAR
            CLEAR_BIT(TIMER1_TCCR1A, TCCR1A_COM1B0);
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1B1);
		#elif TIMER1_CHANNEL_B_OUTPUT_MODE == TIMER1_OC1_SET
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1B0);
            SET_BIT(TIMER1_TCCR1A, TCCR1A_COM1B1);
		#endif
	#endif

    #if TIMER0_PRESCALER == TIMER0_STOP
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_1
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_8
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_64
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_256
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER0_CLK_DIV_BY_1024
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER1_EXT_CLK_T1_FALLING
    CLEAR_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #elif TIMER0_PRESCALER == TIMER1_EXT_CLK_T1_RISISNG
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS10);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS11);
    SET_BIT(TIMER1_TCCR1B, TCCR1B_CS12);

    #endif

/*     #if TIMER1_INTERRUPT == TIMER0_ENABLE_INTERRUPT
    	#if TIMER1_WAVEFORM_MODE == TIMER1_NORMAL
		SET_BIT(TIMERS_TIMSK, TIMSK_TOIE0);
		#elif TIMER1_WAVEFORM_MODE == TIMER1_CTC
		SET_BIT(TIMERS_TIMSK, TIMSK_OCIE0);
    	#endif

    #elif TIMER1_INTERRUPT == TIMER0_DISABLE_INTERRUPT
    	#if TIMER1_WAVEFORM_MODE == TIMER1_NORMAL
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_TOIE0);
		#elif TIMER1_WAVEFORM_MODE == TIMER1_CTC
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_OCIE0);
    	#endif
    #endif */
}

void TIMER1_voidSetInputCaptutreValue(u16 Copy_u16InputCaptureValue)
{
    TIMER1_ICR1 = Copy_u16InputCaptureValue;
}

void TIMER1_voidSetPreloadValue(u16 Copy_u8PreloadValue)
{
    TIMER1_TCNT1 = Copy_u8PreloadValue;
}

void TIMER1_voidSetCompareMatchValue(u16 Copy_u16CompareMatchValue)
{
    TIMER1_OCR1A = Copy_u16CompareMatchValue;
}

void TIMER1_voidSetOVFCallBack(void (*Local_pvoidCallBack) (void));
void TIMER1_voidSetCTCCallBack(void (*Local_pvoidCallBack) (void));

/* TIMER 2 */

void TIMER2_voidInit()
{
    #if TIMER2_WAVEFORM_MODE == TIMER2_NORMAL
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_WGM20);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_WGM21);

    #elif TIMER2_WAVEFORM_MODE == TIMER2_PWM_PHASE_CORRECT
    SET_BIT(TIMER2_TCCR2, TCCR2_WGM20);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_WGM21);

    #elif TIMER2_WAVEFORM_MODE == TIMER2_CTC
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_WGM20);
    SET_BIT(TIMER2_TCCR2, TCCR2_WGM21);

    #elif TIMER2_WAVEFORM_MODE == TIMER2_FAST_PWM
    SET_BIT(TIMER2_TCCR2, TCCR2_WGM20);
    SET_BIT(TIMER2_TCCR2, TCCR2_WGM21);

    #endif

    #if TIMER2_OUTPUT_MODE == TIMER2_NORMAL_OC0_DISCONNECTED
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_COM20);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_COM21);

    #elif TIMER2_WAVEFORM_MODE == TIMER2_TOGGLE_OC0
    	#if	TIMER2_WAVEFORM_MODE == TIMER2_PWM_PHASE_CORRECT || TIMER2_u8_WAVEFORM_MODE == TIMER2_FAST_PWM
		#warning ("RESERVED!")
		#else
        SET_BIT(TIMER2_TCCR2, TCCR2_COM20);
        CLEAR_BIT(TIMER2_TCCR2, TCCR2_COM21);
        #endif

    #elif TIMER2_WAVEFORM_MODE == TIMER2_CLEAR_OC0
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_COM20);
    SET_BIT(TIMER2_TCCR2, TCCR2_COM21);

    #elif TIMER2_WAVEFORM_MODE == TIMER2_SET_OC0
    SET_BIT(TIMER2_TCCR2, TCCR2_COM20);
    SET_BIT(TIMER2_TCCR2, TCCR2_COM21);

    #endif

    #if TIMER2_PRESCALER == TIMER2_STOP
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS00);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS01);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #elif TIMER2_PRESCALER == TIMER2_CLK_DIV_BY_1
    SET_BIT(TIMER2_TCCR2, TCCR2_CS00);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS01);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #elif TIMER2_PRESCALER == TIMER2_CLK_DIV_BY_8
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS00);
    SET_BIT(TIMER2_TCCR2, TCCR2_CS01);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #elif TIMER2_PRESCALER == TIMER2_CLK_DIV_BY_64
    SET_BIT(TIMER2_TCCR2, TCCR2_CS00);
    SET_BIT(TIMER2_TCCR2, TCCR2_CS01);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #elif TIMER2_PRESCALER == TIMER2_CLK_DIV_BY_256
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS00);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS01);
    SET_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #elif TIMER2_PRESCALER == TIMER2_CLK_DIV_BY_1024
    SET_BIT(TIMER2_TCCR2, TCCR2_CS00);
    CLEAR_BIT(TIMER2_TCCR2, TCCR2_CS01);
    SET_BIT(TIMER2_TCCR2, TCCR2_CS02);

    #endif

    #if TIMER2_INTERRUPT == TIMER2_ENABLE_INTERRUPT
    	#if TIMER2_WAVEFORM_MODE == TIMER2_NORMAL
		SET_BIT(TIMERS_TIMSK, TIMSK_TOIE2);
		#elif TIMER2_WAVEFORM_MODE == TIMER2_CTC
		SET_BIT(TIMERS_TIMSK, TIMSK_OCIE2);
    	#endif

    #elif TIMER2_INTERRUPT == TIMER2_DISABLE_INTERRUPT
    	#if TIMER2_WAVEFORM_MODE == TIMER2_NORMAL
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_TOIE2);
		#elif TIMER2_WAVEFORM_MODE == TIMER2_CTC
		CLEAR_BIT(TIMERS_TIMSK, TIMSK_OCIE2);
    	#endif
    #endif
}

void TIMER2_voidSetPreloadValue(u8 Copy_u8PreloadValue)
{
    TIMER2_TCNT2 = Copy_u8PreloadValue;
}

void TIMER2_voidSetCompareMatchValue(u8 Copy_u8CompareMatchValue)
{
    TIMER2_OCR2 = Copy_u8CompareMatchValue;
}

void TIMER2_voidSetOVFCallBack(void (*Local_pvoidCallBack) (void));
void TIMER2_voidSetCTCCallBack(void (*Local_pvoidCallBack) (void));
