/**
 * @file ADC_Config.h
 * @author Khaled Abdulaziz 
 * @brief 
 * @version 0.1
 * @date 2023-04-04
 * 
 * 
 */

#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_

/*  ADC_VREF_AREF_EXTERNAL  0
    ADC_VREF_AVCC  1
    ADC_VREF_INTERNAL 2 */

#define ADC_VOLTAGE_REFERENCE ADC_VREF_AVCC

/*  ADC_RIGHT_ADJUST 0
    ADC_LEFT_ADJUST  1 */

#define ADC_ADJUSTMENT ADC_RIGHT_ADJUST

/*  ADC_ADC0 0
    ADC_ADC1 1
    ADC_ADC2 2
    ADC_ADC3 3
    ADC_ADC4 4
    ADC_ADC5 5
    ADC_ADC6 6
    ADC_ADC7 7 */

#define ADC_CHANNEL ADC_SCM_ADC0

/*  ADC_PRESCALER_2 0
    ADC_PRESCALER_4 1
    ADC_PRESCALER_16 2
    ADC_PRESCALER_32 3
    ADC_PRESCALER_64 4
    ADC_PRESCALER_128 5 */

#define ADC_PRESCALER ADC_PRESCALER_128

/*  ADC_INTERRUPT_DISABLE 0
    ADC_INTERRUPT_ENABLE  1 */

#define ADC_INTERRUPT ADC_INTERRUPT_DISABLE

/*  ADC_SINGLE_CONVERSION_MODE 0
    ADC_FREE_RUNNING_INTERRUPT_MODE  1 */

#define ADC_CONVERSION_MODE ADC_SINGLE_CONVERSION_MODE

/*  ADC_FREE_RUNNING_MODE   0
    ADC_ANALOG_COMPARATOR   1
    ADC_EXTERNAL_INTERRUPT  2
    ADC_TIMER0_CTC          3
    ADC_TIMER0_OVF          4
    ADC_TIMER1_CTC          5
    ADC_TIMER1_OVF          6
    ADC_TIMER1_CE           7 */

#define ADC_AUTO_TRIGGER_SOURCE ADC_FREE_RUNNING_MODE

#endif /* MCAL_ADC_ADC_CONFIG_H_ */
